DATA_PATH = "cleaned_dataset.csv"
RANDOM_STATE = 42
TOP_N_PREDICTIONS = 3
PROBABILITY_THRESHOLD = 0.10
MIN_REQUIRED_SYMPTOMS = 2
MODEL_PROBABILITY_WEIGHT = 0.60
LOW_CONFIDENCE_THRESHOLD = 0.45

# Demo credentials (override in .streamlit/secrets.toml under [auth]).
DEFAULT_USER_USERNAME = "user"
DEFAULT_USER_PASSWORD = "user123"
DEFAULT_ADMIN_USERNAME = "admin"
DEFAULT_ADMIN_PASSWORD = "admin123"
